# Generated by Django 5.2.3 on 2025-08-10 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hours', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hours',
            options={'ordering': ['order'], 'verbose_name': 'Hora', 'verbose_name_plural': 'Horas'},
        ),
        migrations.AddField(
            model_name='hours',
            name='order',
            field=models.PositiveIntegerField(default=1, verbose_name='Orden personalizado'),
        ),
    ]
