# Generated by Django 5.2.3 on 2025-08-10 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hours', '0002_alter_hours_options_hours_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='hours',
            name='is_open',
            field=models.BooleanField(default=True, verbose_name='¿Abierto?'),
        ),
        migrations.AlterField(
            model_name='hours',
            name='order',
            field=models.PositiveIntegerField(default=1, verbose_name='Orden del día'),
        ),
    ]
