# Generated by Django 5.2.3 on 2025-08-10 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hours', '0003_hours_is_open_alter_hours_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hours',
            name='close',
            field=models.TimeField(blank=True, null=True, verbose_name='Hora de cierre'),
        ),
        migrations.AlterField(
            model_name='hours',
            name='open',
            field=models.TimeField(blank=True, null=True, verbose_name='Hora de apertura'),
        ),
    ]
