# Generated by Django 5.1.7 on 2025-08-06 00:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('social_networks', models.CharField(choices=[('facebook', 'Facebook'), ('twitter', 'Twitter'), ('instagram', 'Instagram')], max_length=20, verbose_name='Redes Sociales')),
                ('key', models.SlugField(max_length=100, unique=True, verbose_name='Palabra Clave')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre')),
                ('url', models.URLField(verbose_name='Enlace')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Creado el')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Actualizado el')),
                ('barber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_links', to='about.barbers')),
            ],
            options={
                'verbose_name': 'Enlace',
                'verbose_name_plural': 'Enlaces',
                'ordering': ['name'],
            },
        ),
    ]
