# Generated by Django 5.1.7 on 2025-08-02 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='título')),
                ('description', models.CharField(max_length=100, verbose_name='Descripción')),
                ('content', models.TextField(verbose_name='Contenido')),
                ('since', models.CharField(max_length=50, verbose_name='Desde')),
                ('since_description', models.CharField(max_length=100, verbose_name='Desde_Descripción')),
                ('clients', models.CharField(max_length=50, verbose_name='Número de Clientes')),
                ('clients_description', models.CharField(max_length=100, verbose_name='Clientes_Descripción')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Creado el')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Actualizado el')),
            ],
            options={
                'verbose_name': 'Nosotros',
                'verbose_name_plural': 'Nosotros',
            },
        ),
        migrations.CreateModel(
            name='Barbers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nombre')),
                ('description', models.CharField(max_length=200, verbose_name='Descripción')),
                ('img', models.ImageField(upload_to='Barbers', verbose_name='Foto Empleado')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Creado el')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Actualizado el')),
            ],
            options={
                'verbose_name': 'Barbero',
                'verbose_name_plural': 'Barberos',
            },
        ),
    ]
